# Generated by Django 3.1.7 on 2022-12-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_reportedcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedcar',
            name='reported_issue',
            field=models.CharField(max_length=100),
        ),
    ]
