# Generated by Django 3.1.7 on 2022-12-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20221212_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedcar',
            name='reported_by',
            field=models.CharField(blank=True, default='Godwin Owusu', max_length=50, null=True),
        ),
    ]
